# -*- coding: utf-8 -*-
"""Man_All追加レイヤー(血管/脳神経/臓器/生殖器/未収録筋)の対訳をanatomy_terms.jsonへ統合。"""
import json

PATH = r"C:\Users\abesh\Documents\Blender\MaleAnatomy\scripts\anatomy_terms.json"

# key -> (en, la, conf)  conf: None=確度高 / "low"=要照合
NEW = {
  # ---- 大血管(動脈/静脈) ----
  "上大静脈": ("Superior vena cava", "Vena cava superior", None),
  "下大静脈": ("Inferior vena cava", "Vena cava inferior", None),
  "上行大動脈;大動脈上行部": ("Ascending aorta", "Aorta ascendens", None),
  "下行大動脈;大動脈下行部": ("Descending aorta", "Aorta descendens", None),
  "大動脈弓": ("Aortic arch", "Arcus aortae", None),
  "上腸間膜動脈": ("Superior mesenteric artery", "Arteria mesenterica superior", None),
  "上腸間膜静脈": ("Superior mesenteric vein", "Vena mesenterica superior", None),
  "下腸間膜動脈": ("Inferior mesenteric artery", "Arteria mesenterica inferior", None),
  "腹腔動脈": ("Celiac trunk", "Truncus coeliacus", None),
  "総肝動脈": ("Common hepatic artery", "Arteria hepatica communis", None),
  "脾動脈": ("Splenic artery", "Arteria splenica", None),
  "脾静脈": ("Splenic vein", "Vena splenica", None),
  "胃動脈": ("Gastric artery", "Arteria gastrica", "low"),
  "腎動脈": ("Renal artery", "Arteria renalis", None),
  "腎静脈": ("Renal vein", "Vena renalis", None),
  "内腸骨動脈": ("Internal iliac artery", "Arteria iliaca interna", None),
  "内腸骨静脈": ("Internal iliac vein", "Vena iliaca interna", None),
  "外腸骨動脈": ("External iliac artery", "Arteria iliaca externa", None),
  "外腸骨静脈": ("External iliac vein", "Vena iliaca externa", None),
  "総腸骨動脈": ("Common iliac artery", "Arteria iliaca communis", None),
  "総腸骨静脈": ("Common iliac vein", "Vena iliaca communis", None),
  "総頚動脈": ("Common carotid artery", "Arteria carotis communis", None),
  "内頚静脈": ("Internal jugular vein", "Vena jugularis interna", None),
  "鎖骨下動脈": ("Subclavian artery", "Arteria subclavia", None),
  "鎖骨下静脈": ("Subclavian vein", "Vena subclavia", None),
  "腕頭静脈": ("Brachiocephalic vein", "Vena brachiocephalica", None),
  "腕頭動脈nsn": ("Brachiocephalic trunk", "Truncus brachiocephalicus", None),
  "肺動脈": ("Pulmonary artery", "Arteria pulmonalis", None),
  "肺静脈": ("Pulmonary vein", "Vena pulmonalis", None),
  "肺動脈弁": ("Pulmonary valve", "Valva trunci pulmonalis", None),
  # ---- 冠状血管・心臓 ----
  "冠状動脈主幹": ("Coronary artery (main trunk)", "Arteria coronaria", "low"),
  "冠状動脈の回旋枝": ("Circumflex branch of coronary artery", "Ramus circumflexus", "low"),
  "冠状静脈洞": ("Coronary sinus", "Sinus coronarius", None),
  "大心臓静脈;大心静脈": ("Great cardiac vein", "Vena cordis magna", None),
  "中心臓静脈;中心静脈;後室間静脈": ("Middle cardiac vein", "Vena cordis media", None),
  "前心臓静脈;前心静脈;前右心室静脈": ("Anterior cardiac veins", "Venae cordis anteriores", "low"),
  "心室後静脈;後左心室静脈": ("Posterior vein of left ventricle", "Vena ventriculi sinistri posterior", "low"),
  "中隔室間枝;心室中隔枝;左冠状動脈の前中隔枝": ("Septal interventricular branches (LCA)", "Rami interventriculares septales", "low"),
  "後外側枝;右冠状動脈の右後側壁枝": ("Posterolateral branch (RCA)", "Rami posterolaterales dextri", "low"),
  "縁枝;鋭角縁枝;右冠状動脈の鋭縁枝": ("Right marginal branch (RCA)", "Ramus marginalis dexter", "low"),
  "心室中隔枝;右冠状動脈の中隔室間枝": ("Septal interventricular branches (RCA)", "Rami interventriculares septales", "low"),
  "心室中隔枝nsn;右冠状動脈の中隔室間枝nsn": ("Septal interventricular branch (RCA)", "Rami interventriculares septales", "low"),
  "心室中隔枝nsn;左冠状動脈の中隔室間枝nsn": ("Septal interventricular branch (LCA)", "Rami interventriculares septales", "low"),
  "心臓壁": ("Heart wall (myocardium)", "Paries cordis", "low"),
  "房室弁;三尖弁": ("Tricuspid valve", "Valva tricuspidalis", None),
  "房室弁;僧帽弁;二尖弁": ("Mitral valve", "Valva mitralis", None),
  "心室の前乳頭筋": ("Anterior papillary muscle", "Musculus papillaris anterior", "low"),
  "心室の前乳頭筋nsn": ("Anterior papillary muscle", "Musculus papillaris anterior", "low"),
  "心室の後乳頭筋": ("Posterior papillary muscle", "Musculus papillaris posterior", "low"),
  "心室の中隔乳頭筋": ("Septal papillary muscle", "Musculus papillaris septalis", "low"),
  # ---- 肺 ----
  "肺、上葉": ("Upper lobe of lung", "Lobus superior pulmonis", None),
  "肺、下葉": ("Lower lobe of lung", "Lobus inferior pulmonis", None),
  "中葉［右肺の］/右肺、中葉": ("Middle lobe of right lung", "Lobus medius pulmonis dextri", None),
  # ---- 消化器・体腔臓器 ----
  "肝臓": ("Liver", "Hepar", None),
  "胃": ("Stomach", "Gaster", None),
  "十二指腸": ("Duodenum", "Duodenum", None),
  "空腸": ("Jejunum", "Jejunum", None),
  "回腸": ("Ileum", "Ileum", None),
  "直腸": ("Rectum", "Rectum", None),
  "虫垂": ("Vermiform appendix", "Appendix vermiformis", None),
  "結腸nsn": ("Colon", "Colon", None),
  "胆嚢;タンノウ": ("Gallbladder", "Vesica biliaris", None),
  "膵臓nsn": ("Pancreas", "Pancreas", None),
  "膵管;主膵管": ("Pancreatic duct", "Ductus pancreaticus", None),
  "脾臓": ("Spleen", "Splen", None),
  "食道": ("Esophagus", "Oesophagus", None),
  "気管": ("Trachea", "Trachea", None),
  "気管支": ("Bronchus", "Bronchus", None),
  "横隔膜": ("Diaphragm", "Diaphragma", None),
  "大網ヒモ": ("Omental tenia", "Taenia omentalis", "low"),
  "自由ヒモ": ("Free tenia", "Taenia libera", "low"),
  "間膜ヒモ": ("Mesocolic tenia", "Taenia mesocolica", "low"),
  "胸腺右葉": ("Right lobe of thymus", "Lobus dexter thymi", None),
  "胸腺左葉": ("Left lobe of thymus", "Lobus sinister thymi", None),
  # ---- 泌尿器・内分泌 ----
  "腎臓": ("Kidney", "Ren", None),
  "尿管": ("Ureter", "Ureter", None),
  "尿道": ("Urethra", "Urethra", None),
  "膀胱": ("Urinary bladder", "Vesica urinaria", None),
  "副腎": ("Suprarenal gland", "Glandula suprarenalis", None),
  "下垂体": ("Pituitary gland", "Hypophysis", None),
  "松果体;松果腺": ("Pineal gland", "Glandula pinealis", None),
  # ---- 男性生殖器 ----
  "前立腺": ("Prostate", "Prostata", None),
  "精巣": ("Testis", "Testis", None),
  "精嚢": ("Seminal vesicle", "Glandula vesiculosa", None),
  "精管": ("Ductus deferens", "Ductus deferens", None),
  "副睾丸": ("Epididymis", "Epididymis", None),
  "陰茎亀頭": ("Glans penis", "Glans penis", None),
  "陰茎海綿体": ("Corpus cavernosum penis", "Corpus cavernosum penis", None),
  "尿道海綿体nsn": ("Corpus spongiosum penis", "Corpus spongiosum penis", None),
  "陰毛;カクシゲ": ("Pubic hair", "Pubes", "low"),
  # ---- 脳・神経(CNS) ----
  "小脳": ("Cerebellum", "Cerebellum", None),
  "橋": ("Pons", "Pons", None),
  "髄脳;延髄;球": ("Medulla oblongata", "Medulla oblongata", None),
  "中脳nsn": ("Midbrain", "Mesencephalon", None),
  "脳梁": ("Corpus callosum", "Corpus callosum", None),
  "脳弓": ("Fornix", "Fornix", None),
  "脳弓交連;海馬交連/海馬交連": ("Commissure of fornix (hippocampal commissure)", "Commissura fornicis", "low"),
  "視床": ("Thalamus", "Thalamus", None),
  "視床下部nsn": ("Hypothalamus", "Hypothalamus", None),
  "視床髄条": ("Stria medullaris of thalamus", "Stria medullaris thalami", "low"),
  "海馬": ("Hippocampus", "Hippocampus", None),
  "海馬傍回": ("Parahippocampal gyrus", "Gyrus parahippocampalis", None),
  "扁桃体": ("Amygdala", "Corpus amygdaloideum", None),
  "尾状核": ("Caudate nucleus", "Nucleus caudatus", None),
  "被殻": ("Putamen", "Putamen", None),
  "淡蒼球": ("Globus pallidus", "Globus pallidus", None),
  "島": ("Insula", "Insula", None),
  "帯状回": ("Cingulate gyrus", "Gyrus cinguli", None),
  "視神経": ("Optic nerve", "Nervus opticus", None),
  "視索": ("Optic tract", "Tractus opticus", None),
  "視神経交叉;視交叉": ("Optic chiasm", "Chiasma opticum", None),
  "内側膝状体": ("Medial geniculate body", "Corpus geniculatum mediale", None),
  "外側膝状体": ("Lateral geniculate body", "Corpus geniculatum laterale", None),
  "上丘": ("Superior colliculus", "Colliculus superior", None),
  "下丘": ("Inferior colliculus", "Colliculus inferior", None),
  "上丘腕": ("Brachium of superior colliculus", "Brachium colliculi superioris", "low"),
  "下丘腕": ("Brachium of inferior colliculus", "Brachium colliculi inferioris", "low"),
  "乳頭体": ("Mammillary body", "Corpus mammillare", None),
  "灰白隆起": ("Tuber cinereum", "Tuber cinereum", "low"),
  "終板": ("Lamina terminalis", "Lamina terminalis", "low"),
  "前交連": ("Anterior commissure", "Commissura anterior", None),
  "後交連": ("Posterior commissure", "Commissura posterior", None),
  "手綱": ("Habenula", "Habenula", None),
  "透明中隔": ("Septum pellucidum", "Septum pellucidum", None),
  "脚間窩": ("Interpeduncular fossa", "Fossa interpeduncularis", "low"),
  "大脳脚［広義の］": ("Cerebral peduncle", "Pedunculus cerebri", None),
  "室間孔": ("Interventricular foramen", "Foramen interventriculare", "low"),
  "側脳室": ("Lateral ventricle", "Ventriculus lateralis", None),
  "第N脳室": ("{o} ventricle (brain)", "Ventriculus {r}", "low"),
  "中脳水道;脳水道": ("Cerebral aqueduct", "Aqueductus mesencephali", None),
  "脊髄の中心管": ("Central canal of spinal cord", "Canalis centralis", "low"),
  "分界条": ("Stria terminalis", "Stria terminalis", "low"),
  "大脳半球の脈絡叢": ("Choroid plexus of cerebral hemisphere", "Plexus choroideus", "low"),
  "白質（大脳半球の）": ("White matter (cerebral hemisphere)", "Substantia alba", "low"),
  "内包の前脚;右内包前脚": ("Anterior limb of internal capsule", "Crus anterius capsulae internae", "low"),
  "内包の前脚;左内包前脚": ("Anterior limb of internal capsule", "Crus anterius capsulae internae", "low"),
  # 大脳回(gyri) ※神経解剖の細分 conf:low多め
  "上前頭回": ("Superior frontal gyrus", "Gyrus frontalis superior", None),
  "内側前頭回/右中前頭回": ("Middle frontal gyrus", "Gyrus frontalis medius", "low"),
  "内側前頭回/左中前頭回": ("Middle frontal gyrus", "Gyrus frontalis medius", "low"),
  "上側頭回前部": ("Superior temporal gyrus, anterior part", "Gyrus temporalis superior", "low"),
  "上側頭回後部": ("Superior temporal gyrus, posterior part", "Gyrus temporalis superior", "low"),
  "中側頭回": ("Middle temporal gyrus", "Gyrus temporalis medius", None),
  "下側頭回": ("Inferior temporal gyrus", "Gyrus temporalis inferior", None),
  "中心前回": ("Precentral gyrus", "Gyrus precentralis", None),
  "中心後回": ("Postcentral gyrus", "Gyrus postcentralis", None),
  "縁上回": ("Supramarginal gyrus", "Gyrus supramarginalis", None),
  "角回": ("Angular gyrus", "Gyrus angularis", None),
  "後頭葉": ("Occipital lobe", "Lobus occipitalis", None),
  "上頭頂小葉と楔前部": ("Superior parietal lobule and precuneus", "Lobulus parietalis superior et precuneus", "low"),
  "眼窩回と直回": ("Orbital gyri and gyrus rectus", "Gyri orbitales et gyrus rectus", "low"),
  "副短回": ("Accessory gyrus", "Gyrus accessorius", "low"),
  "側頭葉の外側後頭側頭回": ("Lateral occipitotemporal gyrus", "Gyrus occipitotemporalis lateralis", "low"),
  # ---- 未収録の筋 ----
  "下後鋸筋": ("Serratus posterior inferior", "Musculus serratus posterior inferior", None),
  "肩甲挙筋": ("Levator scapulae", "Musculus levator scapulae", None),
  "大菱形筋": ("Rhomboid major", "Musculus rhomboideus major", None),
  "小菱形筋": ("Rhomboid minor", "Musculus rhomboideus minor", None),
  "腹直筋": ("Rectus abdominis", "Musculus rectus abdominis", None),
  "腹横筋": ("Transversus abdominis", "Musculus transversus abdominis", None),
  "内腹斜筋": ("Internal oblique", "Musculus obliquus internus abdominis", None),
  "錐体筋": ("Pyramidalis", "Musculus pyramidalis", None),
  "鎖骨下筋": ("Subclavius", "Musculus subclavius", None),
  "大後頭直筋": ("Rectus capitis posterior major", "Musculus rectus capitis posterior major", None),
  "小後頭直筋": ("Rectus capitis posterior minor", "Musculus rectus capitis posterior minor", None),
  "頭半棘筋": ("Semispinalis capitis", "Musculus semispinalis capitis", None),
  "頚半棘筋": ("Semispinalis cervicis", "Musculus semispinalis cervicis", None),
  "頚回旋筋": ("Rotatores cervicis", "Musculi rotatores cervicis", "low"),
  "頚最長筋": ("Longissimus cervicis", "Musculus longissimus cervicis", None),
  "胸腸肋筋": ("Iliocostalis thoracis", "Musculus iliocostalis thoracis", None),
  "頚前横突間筋": ("Anterior cervical intertransversarii", "Musculi intertransversarii anteriores cervicis", "low"),
  "頚外側後横突間筋": ("Posterior lateral cervical intertransversarii", "Musculi intertransversarii posteriores laterales cervicis", "low"),
  "頚棘間筋": ("Interspinales cervicis", "Musculi interspinales cervicis", "low"),
  "手の虫様筋": ("Lumbricals of hand", "Musculi lumbricales manus", None),
  "掌側骨間筋": ("Palmar interossei", "Musculi interossei palmares", None),
  "中間腱": ("Intermediate tendon", "Tendo intermedius", "low"),
  # ---- 骨・膜・その他 ----
  "仙骨;仙椎[1－5]": ("Sacrum", "Os sacrum", None),
  "環椎[C1];第N頚椎": ("Atlas (C1)", "Atlas", None),
  "軸椎[C2];第N頚椎": ("Axis (C2)", "Axis", None),
  "下腿骨間膜": ("Interosseous membrane of leg", "Membrana interossea cruris", None),
  "前腕骨間膜": ("Interosseous membrane of forearm", "Membrana interossea antebrachii", None),
  "種子骨(右足の）": ("Sesamoid bone (right foot)", "Os sesamoideum", "low"),
  "種子骨(左足の）": ("Sesamoid bone (left foot)", "Os sesamoideum", "low"),
  "上顎歯肉": ("Maxillary gingiva", "Gingiva", "low"),
  "下顎歯肉": ("Mandibular gingiva", "Gingiva", "low"),
  "眼球": ("Eyeball", "Bulbus oculi", None),
}

def main():
    with open(PATH, encoding='utf-8') as f:
        terms = json.load(f)
    added = 0; over = 0
    for k,(en,la,conf) in NEW.items():
        if k in terms: over += 1
        terms[k] = {"en": en, "la": la, "conf": conf}
        added += 1
    with open(PATH, 'w', encoding='utf-8') as f:
        json.dump(terms, f, ensure_ascii=False, indent=1)
    print(f"added/updated {added} (overwrote {over}). total now {len([k for k in terms if k!='_meta'])}")

if __name__ == '__main__':
    main()
